table Data1
	lineageTag: b303064f-3220-4969-a4f3-8edd95d269d0

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 9e974d84-acc4-4038-8a3e-6994b4c75076
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9a2b42e1-bf4b-4ba4-b329-8924045344b3
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 7b1c940c-af11-47e1-8ab7-388aad1766f0
			defaultHierarchy: LocalDateTable_b7c10b2a-84ee-435e-b2d7-46c637decfc6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Unit Cost'
		dataType: double
		lineageTag: 6a98739c-f9b4-4ac8-b64e-b3389a2fc011
		summarizeBy: sum
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price
		dataType: double
		lineageTag: d3bc430d-4e9c-4666-b21a-47b1c1ee2614
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Qty'
		dataType: int64
		formatString: 0
		lineageTag: 5e9c5b55-ae88-41d6-81d2-528994851608
		summarizeBy: sum
		sourceColumn: Order Qty

		annotation SummarizationSetBy = Automatic

	column 'Cost of Sales'
		dataType: double
		lineageTag: 0ed7e61e-3d8c-4fd6-9b35-fa3a9b0c5622
		summarizeBy: sum
		sourceColumn: Cost of Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 95c7dc4a-4a9f-4190-9530-ecc83b38484c
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 757214a7-d8d6-46ad-a75a-52325a268036
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Channel
		dataType: string
		lineageTag: 8a693422-671c-4629-9067-170767a70c5f
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column 'Promotion Name'
		dataType: string
		lineageTag: 2bf57c22-850c-4ca8-a77b-bb21f03672df
		summarizeBy: none
		sourceColumn: Promotion Name

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: a9da9b45-384e-46cb-8344-0d5e6bf9d176
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: f241397e-5d26-43b7-ad28-b90aff767d52
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column 'Product Sub Category'
		dataType: string
		lineageTag: accb7dcd-e866-4940-9146-2070be1dcb55
		summarizeBy: none
		sourceColumn: Product Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 14fae04a-e934-4c37-a321-9b2798537516
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9ee7fc3e-8d19-4309-9972-ed07cb77c4fd
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 041aff4a-0032-4653-84cf-a744a38dc3eb
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 4808e3e0-1421-4c1e-b1d1-693a4aa90cc3
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition Data1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\BiRi848\Downloads\TrainingData1.xlsx"), null, true),
				    Data_Table = Source{[Item="Data",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Data_Table,{{"Order ID", Int64.Type}, {"Order Date", type date}, {"Unit Cost", type number}, {"Price", type number}, {"Order Qty", Int64.Type}, {"Cost of Sales", type number}, {"Sales", type number}, {"Profit", type number}, {"Channel", type text}, {"Promotion Name", type text}, {"Product Name", type text}, {"Manufacturer", type text}, {"Product Sub Category", type text}, {"Product Category", type text}, {"Region", type text}, {"City", type text}, {"Country", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

